### ISSUE TITLE
Save&publish on Master restart Slave with Azure Directory

### ISSUE THREAD

**Issue by sebaDem27** [Shazwazza/Examine#160] opened 2020-03-24 13:31 UTC
Hello,

When I do a save&publish of a content on the master server, the slave server restart ?
An I see this in the log of slave server. Do you have a solution for me ?

Unhandled exception in AppDomain (terminating)
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 677
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.FetchAttributes(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 1619
   at Examine.AzureDirectory.AzureDirectory.FileLength(String name) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine.AzureDirectory\AzureDirectory.cs:line 291
   at Lucene.Net.Index.TermVectorsTermsWriter.CloseDocStore(SegmentWriteState state)
   at Lucene.Net.Index.TermsHash.CloseDocStore(SegmentWriteState state)
   at Lucene.Net.Index.TermsHash.CloseDocStore(SegmentWriteState state)
   at Lucene.Net.Index.DocInverter.CloseDocStore(SegmentWriteState state)
   at Lucene.Net.Index.DocFieldProcessor.CloseDocStore(SegmentWriteState state)
   at Lucene.Net.Index.DocumentsWriter.CloseDocStore()
   at Lucene.Net.Index.DocumentsWriter.Flush(Boolean closeDocStore)
   at Lucene.Net.Index.IndexWriter.DoFlushInternal(Boolean flushDocStores, Boolean flushDeletes)
   at Lucene.Net.Index.IndexWriter.DoFlush(Boolean flushDocStores, Boolean flushDeletes)
   at Lucene.Net.Index.IndexWriter.PrepareCommit(IDictionary`2 commitUserData, Boolean internal_Renamed)
   at Lucene.Net.Index.IndexWriter.Commit(IDictionary`2 commitUserData)
   at Examine.LuceneEngine.Providers.LuceneIndexer.IndexCommiter.TimerRelease() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 1711
   at Examine.LuceneEngine.Providers.LuceneIndexer.IndexCommiter.<ScheduleCommit>b__7_0(Object _) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 1663
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
Request Information
RequestID:10aed3f8-e01e-0091-46de-01c47f000000
RequestDate:Tue, 24 Mar 2020 13:20:28 GMT
StatusMessage:The specified blob does not exist.
ErrorCode:BlobNotFound

THANKS

**Comment by Shazwazza** [comment] 2020-03-25 00:17
I unfortunately don't have a 'solution' for you but I can see one of the issues. The reason your site restarts is because an exception is occurring on a background thread and it's not handled. When that happens an appdomain will crash. 

This means that a try/catch is going to be needed somewhere in Examine to prevent background threads from crashing an appDomain. Based on the above stack trace we'd need to put a try/catch here https://github.com/Shazwazza/Examine/blob/v0.1.90-azure-directory/src/Examine/LuceneEngine/Providers/LuceneIndexer.cs#L1711 This would be a fail safe place to put the try/catch in case other providers throw.

That said, the original exception looks to be coming from here https://github.com/Shazwazza/Examine/blob/v0.1.90-azure-directory/src/Examine.AzureDirectory/AzureDirectory.cs#L291
Which should also have a try/catch on it similar to this here https://github.com/Shazwazza/Examine/blob/v0.1.90-azure-directory/src/Examine.AzureDirectory/AzureDirectory.cs#L347 IIRC the reason that `FileNotFoundException` is thrown there is because internally lucene handles this in it's own way so I would suggest we follow the same practice on line 291.

Making these changes will help with the errors, but as to why it cannot connect to your blob storage, I'm unsure. The error seems to clearly state `The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
at System.Net.HttpWebRequest.GetResponse()` that it just can't connect to it. Maybe your configuration for your replica/slave servers means they can't communicate with your blob storage?

In the meantime, I have marked this issue as "Help Needed". It would be wonderful if you or anyone (cc @kedigby) could assist with getting these exception handlers in place since I don't think i'm going to have any immediate time to do that.

**Comment by sebaDem27** [comment] 2020-03-25 08:25
I don't know why "Maybe your configuration for your replica/slave servers means they can't communicate with your blob storage?" Because in master and slave I have the same url to the blob storage...

**Comment by sebaDem27** [comment] 2020-03-25 16:29
Hello @Shazwazza ,

I have search and I have find that the file which not exist is an old file.
This file was present before with another implementation of index.
The are several files.

Do you have any idea about this problem ? How resolve this ?

Thanks

**Comment by ykkp2000** [comment] 2020-04-28 12:44
Hello,
I have a similar problem on my site, i debugged the package, and what I 'think' the issue is, is the local cache that's stored in the temp folder. It looks like that when the data in the cache and blob is out of sync, it goes wrong. i.e. a file is in temp storage, but not in the blob, and is flagged as out of sync, it's trying to download the file from the blob, rather than deleting the file from the cache.

**Comment by Shazwazza** [comment] 2020-06-12 00:04
@ykkp2000 I guess if the blob storage index has entirely changed from the local index (the only way this is normally possible is if the index is rebuilt by another 'master' server or it's optimized by another master server). Perhaps in this case where the whole thing is vastly out of sync it 'starts again' and clears the local files and re-syncs from scratch. I haven't looked at this code in quite some time so if anyone has time to help with any PR or code changes it would be great.

**Comment by bielu** [comment] 2020-07-24 11:22
@Shazwazza I actually was able to reproduce that issue with big index and only one master server, my indexes are arround 150mb and everytime when I published something from Umbraco I get optimalization of lucene and structure of files was not sync and it was forcing re-sync from scratch and taking app down as time out was hitted.

**Comment by Shazwazza** [comment] 2020-08-27 02:39
@bielu thanks for the info. So to confirm, for some reason Lucene is optimizing your index? I know when this happens the files are all restructured but in Examine it specifically does not optimize the index. There is a method for it here https://github.com/Shazwazza/Examine/blob/14d346fd6b763b37fb841c0e1e4b040007f81ba8/src/Examine/LuceneEngine/Providers/LuceneIndex.cs#L475 but that is never called. In the 0.9 version a long time ago optimize was called on occasion but that hasn't been done for a long time. I don't think Lucene auto-optimizes either and I believe it leaves it up to the caller to perform that if they choose. What do you think?

**Comment by bielu** [comment] 2020-08-27 10:35
@Shazwazza Lucene auto-optimizes when you write that for some reason, even if imho shouldn't :) but yeah everytime when I am seeing writing to index I am seeing first small file(I believe they are called segments) create next to big one and later merged with next writing :)

**Comment by Shazwazza** [comment] 2020-08-27 11:36
@bielu hrm, it didn't in 2.9 and afaik it still shouldn't do any optimizations itself unless you tell it to. The docs for 3.x also seem to state this https://lucene.apache.org/core/3_0_3/api/core/org/apache/lucene/index/IndexWriter.html
Also to confirm - are you talking about umb v8 with examine 1 or umb v7 with examine 0.9?

**Comment by Shazwazza** [comment] 2020-08-27 11:46
I think possibly what's being seen is lucene merging documents, i will need to investigate the different merge policies and see what actually happens. lucene file system is supposed to be write-once but i guess if there's merging going on outside of optimization then this may not be completely true.

**Comment by bielu** [comment] 2020-08-27 11:49
@Shazwazza I saw similar behavior on both but more often on umb v7 with 0.9 :) on v8 I think I saw that only once and sure if it was cause by some settings or something, but yeah on v7 it is casual.

**Comment by Shazwazza** [comment] 2020-08-27 11:50
With the syncing directories though, merging in theory shouldn't be an issue since the files will be persisted to both directories so the theory is they shouldn't get out of sync and cause issues but I guess it's something to investigate and confirm any issues.

**Comment by bielu** [comment] 2020-08-27 11:52
@Shazwazza that is partially true, as if you loadbalance it will get out the sync :) as it will update only on the writer on reader it will get out the sync(ReadOnlyDirectory)

**Comment by Shazwazza** [comment] 2020-08-27 11:59
Ah yes i think i see what you mean since the replica servers are only going to write to their own local index and not the master index but since the master index has now changed, things can get weird. Is that what you mean?  Once quick solution is to use the NoMergePolicy https://lucene.apache.org/core/3_3_0/api/core/org/apache/lucene/index/NoMergePolicy.html , the other is to check if the replica node should do a full re-sync

**Comment by bielu** [comment] 2020-08-27 12:06
@Shazwazza yeah I mean the replica will get out the sync as merge policy will apply on master, I think we should do some tricks on that in Examine Directory and NoMergePolicy sounds like good start :). as my replica servers will not index anything to themselves :)

**Comment by Shazwazza** [comment] 2020-08-27 12:17
The replica servers do index, they maintain their own local index and they write to that. They write based on the instructions in the instructions queue table based on the umbraco cache refreshers.

**Comment by Shazwazza** [comment] 2020-08-27 12:18
(it is late here so my brain isn't totally working, i might be saying the wrong thing :P )

**Comment by bielu** [comment] 2020-08-27 12:30
Ok, it make sense, but not sure if enabling NoMergePolicy will help not in that situation as if you think about that, segments can be different (If I understand correctly how segments in lucene works), but I can misunderstand logic here, behind that

**Comment by Shazwazza** [comment] 2020-08-28 05:09
@bielu ok have looked into this further and have figured some things out. Since i haven't looked at this for a while i had to get my head back into it. I was confusing the typical SyncDirectoryFactory with the AzureDirectory stuff. SyncDirectoryFactory works slightly differently because it's only a single web app that will read and write to main + local whereas with AzureDirectory it should be only one web app that writes to main but many can read from it.

... And this is where some things need to change. I've created a unit test that we can expand upon which shows some of the issues. I've already fixed a couple locally but there is still an issue which is that Umbraco replica instances will always attempt to write to the local index because it is configured as such to think that each server maintains it's own index. This concept doesn't quite work for the AzureDirectory concept (just like ExamineX has to work around this too). Currently what the Examine Azure Directory implementation does is it that in readonly mode it will still write to the local index because it doesn't know what else to do. In doing this things can get a bit whacky and inevitably errors will occur. So instead what needs to happen is when it's in readonly mode any writes do not do anything and just flags the index as 'dirty' so that it resync's from main storage next time. 

I'm working on an update and will push some changes soon.

**Comment by Shazwazza** [comment] 2020-08-28 05:57
I have created this test https://github.com/Shazwazza/Examine/blob/v0.1.91/src/Examine.Test/AzureDirectory/ReadOnlyTest.cs#L40 which is now passing but this would not have passed before with the recent changes. Like I said above, the readonly instances cannot write to the index but that is out of Examine's control since Umbraco decides on that. These recent changes try to avoid this by using Noop IndexOutput however that is not good enough since we'll still get a lucene exception when the index tries to commit (even though nothing has really been written). There's probably some awful work around to that but it's actually much easier to just disable indexing with an event which you can see I've done here https://github.com/Shazwazza/Examine/blob/v0.1.91/src/Examine.Test/AzureDirectory/ReadOnlyTest.cs#L80 . This would be a requirement for the replica instances but it's possible to ensure this happens somewhere within the readonly directory factory so it's automatic. 

Let me know what you think.

**Comment by bielu** [comment] 2020-08-28 10:03
@Shazwazza idea sound ok and I think we should go for both:
No Merge policy and disable writing in Azure Directory :)

**Comment by jsheard02** [comment] 2020-09-18 09:38
Interested to know if there was any further progress made on this ?

**Comment by Shazwazza** [comment] 2020-09-21 13:01
I'm spending a bit of time this week going through some of the issues, i'll report back later on to see if I get as far as getting this one updated.

**Comment by Shazwazza** [comment] 2021-08-24 16:12
Going to close this issue - it is a known issue and the Examine project itself isn't going to move forward with support for the Azure Directory project. Instead the plan is that this project will be managed externally to the Examine project. See https://github.com/Shazwazza/Examine/pull/226

**Closed by Shazwazza** 2021-08-24 16:12 UTC
Labels: bug, help wanted
