### ISSUE TITLE
Search with danish char.

### ISSUE THREAD

**Issue by lucasmichaelsengorm** [Shazwazza/Examine#244] opened 2021-09-14 10:17 UTC
Hello, 
I have discorved something strange, when working whit Umbraco, where a customer said. Hey i do not get any result when i search word thats contains Æ, Ø or Å.

I have try many diffendt thing, and i can see it is not an Umbraco related issue, that why i am here.

So the words i try to search is "Rådgivning", witch is giving 0 results.
If i search for the word "Radgivning", it gives result.

Okay so here is what i tried to do, in Examine solutions

        [Test]
        public void lumi()
        {
            var analyzer = new StandardAnalyzer(Version.LUCENE_30);
            using (var luceneDir = new RandomIdRAMDirectory())
            using (var indexer = new TestIndex(luceneDir, new CultureInvariantWhitespaceAnalyzer()))

            {
                indexer.IndexItems(new[] {
                    ValueSet.FromObject(1.ToString(), "content",
                        new { nodeName = "løn til dig som privat person", bodyText = "It was one thing to bring Carmen into it, but Jonathan was another story.", __NodeTypeAlias = "pSectionPage" }),
                    ValueSet.FromObject(2.ToString(), "content",
                        new { nodeName = "næste jobmulighed", bodyText = "Hands shoved backwards into his back pockets, he took slow deliberate steps, as if he had something on his mind.", __NodeTypeAlias = "pSectionPage" }),
                    ValueSet.FromObject(3.ToString(), "content",
                        new { nodeName = "åbnen huse", bodyText = "Slowly carrying the full cups into the living room, she handed one to Alex.", __NodeTypeAlias = "pSectionWithSideNavigationPage" })
                    });

                var searcher = indexer.GetSearcher();

                var criteria = searcher.CreateQuery();

                // TODO: This isn't testing correctly because the search parser is actually removing stop words to generate the search so we actually
                // end up with an empty search and then by fluke this test passes.
                var filter = criteria.Field("nodeName", "næste".MultipleCharacterWildcard()).And().Field("bodyText", "næste".MultipleCharacterWildcard());

                Console.WriteLine(filter);

                var results = filter.Execute();
                var test3 = indexer.GetSearcher().CreateQuery().ManagedQuery("løn", new string[] { "bodyText", "nodeName" });
                var test = indexer.GetSearcher().CreateQuery().NativeQuery("nodenName:næste*").Execute();
                var test1 = indexer.GetSearcher().Search("næste", 100);

                Assert.AreEqual(1, results.TotalItemCount);
            }
        }

if we take it from the top:
results is the Query: +nodeName:næste* +bodyText:næste* and return 0.
test3 is the Query: +((+bodyText:"løn") (+nodeName:"løn")) and return 0.
test is the Query: +nodeName:næste* and return 0
test1 is the Query: +((nodeName:"naeste"^20.0 +(nodeName:naeste^10.0 nodeName:naeste*)) (bodyText:"naeste"^20.0 +(bodyText:naeste^10.0 bodyText:naeste*))) witch gives result.

But somehow is you only you the .search func. it convert æ to ae as exceptede, but test3 do that not happend any thing.

Just as a reff. the code from the customer, where æ stay æ in Umbraco

       public ContentSearch GetResults(ContentSearch contentSearch, string cultureName = "da-dk")
        {
            // init the examine manager instance
            IExamineManager examineManager = ExamineManager.Instance;

            // Check first if the examine ExternalIndex exists
            if (!examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out IIndex index))
                throw new InvalidOperationException($"No index found by name {Constants.UmbracoIndexes.ExternalIndexName}");

            // Get the searcher
            var searcher = index.GetSearcher();

            // Define the criteria
            var criteria = searcher.CreateQuery(IndexTypes.Content, BooleanOperation.And);

            // Define searchable nodes
            string[] searchableNodes = new string[] {
                PSectionPage.ModelTypeAlias,
                PSectionWithSideNavigationPage.ModelTypeAlias
            };

            // Define searchable fields
            string[] searchableFields = new[] {
                $"nodeName",
                $"{PSectionWithSideNavigationPage.GetModelPropertyType(x=>x.PSectionWithSideNavigationPageContent).Alias}_{cultureName}",
                $"{PSectionWithSideNavigationPage.GetModelPropertyType(x=>x.PSectionWithSideNavigationPageSections).Alias}_{cultureName}",
                $"{PSectionPage.GetModelPropertyType(x=>x.PSectionPageSections).Alias}_{cultureName}"
            };

            // Filter by node type
            var examineQuery = criteria.GroupedOr(new string[] { "__NodeTypeAlias" }, searchableNodes);

            // Check if we have a query
            if (!string.IsNullOrEmpty(contentSearch.SearchTerm))
            {
                if (contentSearch.SearchTerm.Contains(" "))
                {
                    string[] terms = contentSearch.SearchTerm.Split(' ');

                    examineQuery.And().GroupedOr(searchableFields, terms);
                }
                else
                {
                    examineQuery.And().Field(searchableFields[0], contentSearch.SearchTerm.ToSafeAlias().MultipleCharacterWildcard())
                        .Or().Field(searchableFields[1], contentSearch.SearchTerm.MultipleCharacterWildcard())
                        .Or().Field(searchableFields[2], contentSearch.SearchTerm.MultipleCharacterWildcard())
                        .Or().Field(searchableFields[3], contentSearch.SearchTerm.MultipleCharacterWildcard());
                }
            }

            // Excecute the search
            ISearchResults searchResult = examineQuery.Execute();
            IEnumerable<ISearchResult> results = searchResult;

**Comment by Shazwazza** [comment] 2021-09-20 15:48
Hi thanks for the report.

In your test above your query is:

```cs
var filter = criteria.Field("nodeName", "næste".MultipleCharacterWildcard()).And().Field("bodyText", "næste".MultipleCharacterWildcard());
```

but your test data doesn't contain any 'bodyText'. That said though, I can confirm there is some issue where and it has to do with wilcard queries while using the CultureInvariantWhitespaceAnalyzer.

For example, this works:

```cs
var filter = criteria.Field("nodeName", "næste");
Console.WriteLine(filter);
var results = filter.Execute();
```

But this doesn't:

```cs
var filter = criteria.Field("nodeName", "næste".MultipleCharacterWildcard());
Console.WriteLine(filter);
var results = filter.Execute();
```

But this does:

But this doesn't:

```cs
var filter = criteria.Field("nodeName", "privat".MultipleCharacterWildcard());
Console.WriteLine(filter);
var results = filter.Execute();
```

It is possible to change the analyzer for any given index. I'll need to investigate why wildcards behave a little differently when using the `CultureInvariantWhitespaceAnalyzer`. For the time being, you could try to just use the StandardAnalyzer for the index the customer is using to search.

**Comment by Shazwazza** [comment] 2021-09-20 16:15
The issue is that Lucene on purpose does not run the search value through the analyzer for wildcard queries. 

See:

https://stackoverflow.com/questions/28650774/lucene-query-parser-to-use-filters-for-wildcard-queries
https://stackoverflow.com/questions/9103495/using-a-combination-of-wildcards-and-stemming
https://lists.archive.carbon60.com/lucene/java-user/14224

There's no perfect solution to this either since doing this might cause other unwanted results. Perhaps the easiest solution for you is to change the internal index to use the StandardAnalyzer instead.

**Comment by lucasmichaelsengorm** [comment] 2021-09-22 13:31
Hello @Shazwazza 

I have tried now some diffendt things, and discovered something
I have create a test inside FluentApiTests file in version 1.2.1, on my local machine
        
     public void lumiv2()
     {
            var analyzer = new StandardAnalyzer(Version.LUCENE_30);
            using (var luceneDir = new RandomIdRAMDirectory())
            using (var indexer = new TestIndex(luceneDir, new StandardAnalyzer(Version.LUCENE_30)))
            {
                indexer.IndexItems(new[] {
                    new ValueSet(1.ToString(), "content", new Dictionary<string, object>{
                        { "nodeName", "LØNSIKRING" },
                        { "bodyText", "Som medlem af FTFa kan du få dækning på helt op til 90 % af din løn med en lønsikring hos FTFa." },
                    }),
                    new ValueSet(2.ToString(), "content", new Dictionary<string, object>{
                        {"nodeName", "BETALING AF LØNSIKRING" },
                        {"bodyText", "Du kan få FTFa Lønsikring fra kr. 79 om måneden for en dækning på kr. 2.000. Alt efter din nuværende løn, kan du tegne en dækning på op til kr. 40.000 om måneden, som koster kr. 1.578 månedligt. Eksempelvis koster det kr. 395 kr før fradrag i skat for en dækning på kr. 10.000 pr.måned. Du kan selv prøve at beregne din ønskede dækning her"},
                    }),
                    new ValueSet(3.ToString(), "content", new Dictionary<string, object>{
                        {"nodeName", "UDBETALINGER FRA LØNSIKRING" },
                        {"bodyText", "Lønsikringen træder i kraft den 1. i måneden efter tegningsdagen. Herefter starter din kvalifikationsperiode, som er de første 9 måneder, hvor du betaler til forsikringen. I den periode kan du ikke få udbetalt lønsikring." },
                    })
                });

                var test = indexer.GetSearcher().CreateQuery().NativeQuery("nodenName:løn*").Execute().TotalItemCount;
                var test1 = indexer.GetSearcher().Search("løn").TotalItemCount;
                var test3 = indexer.GetSearcher().CreateQuery().ManagedQuery("løn", new string[] { "bodyText", "nodeName" }).Execute().TotalItemCount;
                var test4 = indexer.GetSearcher().CreateQuery().Field("nodeName", "løn".MultipleCharacterWildcard()).And().Field("bodyText", "løn".MultipleCharacterWildcard()).Execute().TotalItemCount;
                var test5 = indexer.GetSearcher().CreateQuery().Field("nodeName", "løn").And().Field("bodyText", "løn").Execute().TotalItemCount;
                var test6 = indexer.GetSearcher().CreateQuery().NativeQuery("nodeName:lon*").Execute().TotalItemCount;

                Assert.AreEqual(1, 1);
            }
        }
        
First I tried with the `StandardAnalyzer` let it parse diffendt method and here is the query and results
| variable | query | results|
|-------|------|------|
| test | +nodenName:løn* | 0 |
| test1 | +((+nodeName:"løn") (+bodyText:"løn"))  | 2 |
| test3 | +((+bodyText:"løn") (+nodeName:"løn")) | 2 |
| test4 | +nodeName:løn* +bodyText:løn*| 3 |
| test5 | +nodeName:løn +bodyText:løn | 0 |
| test6 | nodeName:lon* | 0 |

Then I tried to replace the `StandardAnalyzer`  with `CultureInvariantStandardAnalyzer` and let it parse the same index and methoeds, and the queries and result:

| variable | query | results|
|-------|------|------|
| test | +nodenName:løn* | 0 |
| test1 | +((+nodeName:"løn") (+bodyText:"løn")) | 0 |
| test3 | +((+bodyText:"løn") (+nodeName:"løn")) | 0 |
| test4 | +nodeName:løn* +bodyText:løn*| 0 |
| test5 | +nodeName:lon +bodyText:lon  | 0 |
| test6 |  nodeName:lon* | 3 |


It worked more promising with the `StandardAnalyzer` and with `MultipleCharacterWildcard`.
Where `CultureInvariantStandardAnalyzer` is parsing the searchTerm, on Test5 where i´m not using the `MultipleCharacterWildcard` func.  But then Lucen as expetec can´t match results.

I´ll try to go back to my Umbraco Installation and teest alittle bit more out.
Stay tuned

**Comment by lucasmichaelsengorm** [comment] 2021-09-23 07:27
Hello @Shazwazza,

I have search a little bit deeper, and I have concluded that your package is working as attended, and it is Umbraco witch have some problems, I´ll therefor close this issue for now, and open an issue on Umbraco to have a discussion about the findings. 

What I discovered is that whit the test above, on test4 everything is working as I expected it to be.
When I look down in the index of the FieldAnalyzer, I could see the Field is store as "nodeName" with the StandardAnalyzer, on the Examine project.

Do I go to my Umbraco Installation, and look down in the FieldAnalyzer on the Field "nodeName" then it is stored with the CultureInvariantStandardAnalyzer. _Near all Field in Umbraco External index is stored with the CultureInvariantStandardAnalyzer but the index is set to be with StandardAnalyzer_

I also tried to changes the above show test, to have a `new FieldDefinitionCollection(new FieldDefinition("nodeName", FieldDefinitionTypes.InvariantCultureIgnoreCase))` so the Field "NodeName" have the CultureInvariantStandardAnalyzer and the Index have the "StandardAnalyzer" just a like Umbraco and the result is not like expected: 
|variable | query | results|
-- | -- | --
| test | +nodenName:løn* | 0 |
| test1 | +(nodeName:løn (+bodyText:"løn")) | 2 |
| test3 | +((+bodyText:"løn") nodeName:løn) | 2 |
| test4 | +nodeName:løn* +bodyText:løn* | 0 |
| test5 | +nodeName:lon +bodyText:løn | 0 |
| test6 | +nodeName:lon* | 3 |

But in the end thanks @Shazwazza for pointing me to the right track to debug for the kind of freaky issue 😄

**Comment by Shazwazza** [comment] 2021-09-23 15:10
closing issue, we can discuss on the umbraco tracker.

**Closed by Shazwazza** 2021-09-23 15:10 UTC
Labels: question
