### ISSUE TITLE
Umbraco Members index is rebuilt when restarting the Azure Web App

### ISSUE THREAD

**Issue by stefankip** [Shazwazza/Examine#215] opened 2021-03-15 11:04 UTC
Hi!

We're running an Umbraco website on Azure Web Apps. The `<add key="Umbraco.Examine.LuceneDirectoryFactory" value="Examine.LuceneEngine.Directories.SyncTempEnvDirectoryFactory, Examine" />` setting is in place and I also see this inside the Examine dashboard: `LuceneDirectory: SyncDirectory`.
Whenever the application is restarted, the Members index gets rebuild. I don't know why this is happening, but it's killing the website, because this process takes like 15 minuten to complete because of the amount of members.

So question is; why is the index rebuilt when the web app is restarted? There's a 'master' index on the network share right?

**Comment by Shazwazza** [comment] 2021-03-15 22:03
Hi! I can try to help here but this question is all about Umbraco itself. Examine doesn't perform any logic for rebuilding indexes on startup, that is all controlled by Umbraco, along with the configuration mentioned here. 

> Whenever the application is restarted, the Members index gets rebuild.

* Is it just the member index that is doing this?
* Is there anything in your logs on startup that might indicate why this is happening? Like running a cold boot?

> There's a 'master' index on the network share right?

In theory but if there isn't one then a rebuild will need to occur. The `SyncTempEnvDirectoryFactory` lazily copies over files from the main drive to the local %temp% storage when lucene requests those files so all lucene operations work based on the files on the local fast drive.

(I'll see if I can transfer this issue to the CMS repo)

**Comment by Shazwazza** [comment] 2021-03-15 22:05
Nope that doesn't work. I'll close this issue here but feel free to respond about the questions above and I can try to help but if it's an issue with the CMS then you'll need to open a new issue there.

**Closed by Shazwazza** 2021-03-15 22:05 UTC
Labels: question

**Comment by stefankip** [comment] 2021-03-16 09:10
@Shazwazza I have looked at the logs, but don't see if it's a cold boot. I do see this:

> No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.
> Source: Umbraco.Core.Sync.DatabaseServerMessenger

and

> Forcing index "MembersIndex" to be unlocked since it was left in a locked state

Not sure what to look for besides this, do you have any hints?

**Comment by Shazwazza** [comment] 2021-03-17 00:04
Hi, yes this log msg:

> No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.
Source: Umbraco.Core.Sync.DatabaseServerMessenger

indicates that a cold boot will take place. this would also indicate that all of your indexes are rebuilt, not just the members. 

> Is it just the member index that is doing this?

Can you confirm?

You can see the source for that warning here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Sync/DatabaseServerMessenger.cs#L181

the last synced id is read from a file here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Sync/DatabaseServerMessenger.cs#L495

The file is saved to this location: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Sync/DatabaseServerMessenger.cs#L533

On azure [this setting should be enabled](https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps#recommended-configuration):

```xml
<add
    key="Umbraco.Core.LocalTempStorage"
    value="EnvironmentTemp" />
```

which means the file will be stored in the local temp storage, that path is calculated here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Configuration/GlobalSettings.cs#L317  which on azure will be the local fast drive. 

This does mean though that when your site moves between workers it will cold boot because that file will not be there. In most ways this is by design because the nucache files will need to be rebuilt locally on the new temp environment, but the indexes in the case where `SyncTempEnvDirectoryFactory` is used probably shouldn't be rebuilt. Interesting. I think that could be a check in Umbraco to deal with that.

I'm unsure if that is your issue though since you say this happens "Whenever the application is restarted". Perhaps this is related though since if you are seeing this log entry "Whenever the application is restarted" that means that something else strange is happening and the lastsynced.txt file isn't being resolved.

There is an old task in the Umbraco tracker to change how the lastsynced data is stored and use the database per server instead which would be much more ideal: https://github.com/umbraco/Umbraco-CMS/issues/5263 but that said, the current lastsynced.txt file should work as it's supposed to.

Hopefully this gives you some info for your investigation. Please let me know what you find. Also please open an issue on the umbraco tracker for the cold boot issue with SyncTempEnvDirectoryFactory mentioned above if you have time. Cheers!
